In [1]:
!pip install numpy

In [2]:
# Задание 1
import numpy as np
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])
print(a)
print('Dimension', format(a.ndim))  # Размерность
print('Shape', format(a.shape))     # Форма

mean_a = np.mean(a, axis=0)         # Ищем среднее значение по каждому признаку
# np.mean(a, axis=0, out=mean_a)
print(mean_a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Dimension 2
Shape (5, 2)
[2.  8.4]


In [3]:

# Задание 2
a_centered = a - mean_a
print(a_centered)


[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [4]:
# Задание 3
from functools import reduce
a_centered_sp = 0
multiplication = 0
for i in a_centered:
  multiplication = reduce(lambda x, y: x*y, i)
  # print(multiplication)
  a_centered_sp += multiplication
print('Scalar multiplication is', a_centered_sp)
covariation = a_centered_sp / 4
print('Covariation is', covariation)

Scalar multiplication is 8.0
Covariation is 2.0


In [5]:
# Задание 4
arr_transpose = a.transpose()  # Траспонируем матрицу с помощью функции transpose()
print(arr_transpose)
arr_cov = np.cov(arr_transpose) # Вычисляем ковариацию с помощью функции np.cov()
print(arr_cov)
print('Covariation is', arr_cov[0][1])

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
[[1.  2. ]
 [2.  4.3]]
Covariation is 2.0
