1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

a = np.arange(12, 24, 1)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [12]:
ar1 = a.reshape(3, 4)
print(ar1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
ar2 = a.reshape(4, 3)
print(ar2)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [14]:
ar3 = a.reshape(2, 6)
print(ar3)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [15]:
ar4 = a.reshape(6, 2)
print(ar4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [16]:
ar5 = a.reshape(12, 1)
ar5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [17]:
ar1 = a.reshape(12, -1)
print(ar1)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [18]:
ar2 = a.reshape(3, -1)
print(ar2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
ar3 = a.reshape(4, -1)
print(ar3)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [20]:
ar4 = a.reshape(-1, 6)
print(ar4)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [21]:
ar5 = a.reshape(-1, 2)
print(ar5)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [22]:
# Нет нельзя, так как это легко можно проверить используя методы ndim и shape
ar1 = a.reshape(12, -1)
print(ar1)
print("Размерность ar1: {}".format(ar1.ndim))
print(f'Форма ar1: ', format(a.shape))

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Размерность ar1: 2
Форма ar1:  (12,)


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив

In [23]:
a = np.random.randn(3, 4)
a

array([[-1.11188012,  0.31890218,  0.27904129,  1.01051528],
       [-0.58087813, -0.52516981, -0.57138017, -0.92408284],
       [-2.61254901,  0.95036968,  0.81644508, -1.523876  ]])

In [24]:
a.size

12

In [25]:
b = a.reshape(12)
print(b)


[-1.11188012  0.31890218  0.27904129  1.01051528 -0.58087813 -0.52516981
 -0.57138017 -0.92408284 -2.61254901  0.95036968  0.81644508 -1.523876  ]


In [26]:
# Ещё один вариант
c = a.flatten()
print(c)

[-1.11188012  0.31890218  0.27904129  1.01051528 -0.58087813 -0.52516981
 -0.57138017 -0.92408284 -2.61254901  0.95036968  0.81644508 -1.523876  ]


In [27]:
b.size
# c.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [28]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [29]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [30]:
type(a) == type(b)

True

In [31]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [32]:
a.shape == b.shape

True

In [33]:
a.ndim == b.ndim

True

In [34]:
a.size == b.size

True

Между массивами a и b нет разницы

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

In [35]:
a = np.zeros((5))
b = np.ones((5))


In [36]:
v = np.vstack((a, b))
v

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [37]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [38]:
a = np.arange(0, 12, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [41]:
B = np.matmul(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [33]:
B.size

16

In [42]:
B.shape

(4, 4)

In [43]:
# Вычислим определитель матрицы

BB = np.linalg.det(B)
BB

0.0

Определитель матрицы равен 0, значит обратной матрицы для матрицы B не существует. Мы это можем проверить используя функцию inv(), который вызовет исключение 'Singular matrix'

In [44]:
Binv = np.linalg.inv(B)
Binv

LinAlgError: ignored

10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42

---



In [45]:
np.random.seed(42)
print(np.random.random())

0.3745401188473625


11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [58]:
c = np.random.normal(0, 16, size = 16)
c

array([ -0.2159556 , -16.92337486,  13.16071859, -19.5334984 ,
         3.34181752, -31.35472198, -21.25097678,   3.14977977,
        11.81546528,   2.7418925 ,  -1.85037252,  -4.81765913,
       -23.65635185, -11.51750733,  -7.37022034,  16.91395562])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D

In [59]:
C = c.reshape(4, 4)
C

array([[ -0.2159556 , -16.92337486,  13.16071859, -19.5334984 ],
       [  3.34181752, -31.35472198, -21.25097678,   3.14977977],
       [ 11.81546528,   2.7418925 ,  -1.85037252,  -4.81765913],
       [-23.65635185, -11.51750733,  -7.37022034,  16.91395562]])

In [60]:
D = B + (C * 10)
D

array([[   2.84044404, -155.23374863,  154.60718594, -163.334984  ],
       [  47.4181752 , -263.54721982, -126.50976782,  153.49779774],
       [ 141.1546528 ,  113.41892499,  130.49627482,  163.82340871],
       [-204.56351846,    6.82492666,  138.29779665,  471.1395562 ]])

In [61]:
d = np.linalg.det(D)
d

9984392717.672071

In [62]:
r = np.linalg.matrix_rank(D)
r

4

In [63]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[-0.00013447  0.00165582  0.00377782 -0.0018997 ]
 [-0.00216218 -0.00229374  0.00053908 -0.00018973]
 [ 0.00325998 -0.00117458  0.00167657  0.00092988]
 [-0.000984    0.00109695  0.00114034  0.00102748]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C

In [ ]:
# Не успеваю сделать это задание :(